<?php

// scoper-autoload.php @generated by PhpScoper

$loader = (static function () {
    // Backup the autoloaded Composer files
    $existingComposerAutoloadFiles = $GLOBALS['__composer_autoload_files'] ?? [];

    $loader = require_once __DIR__.'/autoload.php';
    // Ensure InstalledVersions is available
    $installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
    if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;

    // Restore the backup and ensure the excluded files are properly marked as loaded
    $GLOBALS['__composer_autoload_files'] = \array_merge(
        $existingComposerAutoloadFiles,
        \array_fill_keys([], true)
    );

    return $loader;
})();

// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
if (!function_exists('humbug_phpscoper_expose_class')) {
    function humbug_phpscoper_expose_class($exposed, $prefixed) {
        if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
            spl_autoload_call($prefixed);
        }
    }
}
humbug_phpscoper_expose_class('ComposerAutoloaderInitd5aef0df7ce5eceac79ec8466d3a7142', 'PhpScoperExampleVendor\ComposerAutoloaderInitd5aef0df7ce5eceac79ec8466d3a7142');
humbug_phpscoper_expose_class('ReflectionConstant', 'PhpScoperExampleVendor\ReflectionConstant');
humbug_phpscoper_expose_class('Deprecated', 'PhpScoperExampleVendor\Deprecated');
humbug_phpscoper_expose_class('NoDiscard', 'PhpScoperExampleVendor\NoDiscard');

// Function aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#function-aliases
if (!function_exists('array_all')) { function array_all() { return \PhpScoperExampleVendor\array_all(...func_get_args()); } }
if (!function_exists('array_any')) { function array_any() { return \PhpScoperExampleVendor\array_any(...func_get_args()); } }
if (!function_exists('array_find')) { function array_find() { return \PhpScoperExampleVendor\array_find(...func_get_args()); } }
if (!function_exists('array_find_key')) { function array_find_key() { return \PhpScoperExampleVendor\array_find_key(...func_get_args()); } }
if (!function_exists('array_first')) { function array_first() { return \PhpScoperExampleVendor\array_first(...func_get_args()); } }
if (!function_exists('array_last')) { function array_last() { return \PhpScoperExampleVendor\array_last(...func_get_args()); } }
if (!function_exists('bcdivmod')) { function bcdivmod() { return \PhpScoperExampleVendor\bcdivmod(...func_get_args()); } }
if (!function_exists('collect')) { function collect() { return \PhpScoperExampleVendor\collect(...func_get_args()); } }
if (!function_exists('data_fill')) { function data_fill() { return \PhpScoperExampleVendor\data_fill(...func_get_args()); } }
if (!function_exists('data_forget')) { function data_forget() { return \PhpScoperExampleVendor\data_forget(...func_get_args()); } }
if (!function_exists('data_get')) { function data_get() { return \PhpScoperExampleVendor\data_get(...func_get_args()); } }
if (!function_exists('data_has')) { function data_has() { return \PhpScoperExampleVendor\data_has(...func_get_args()); } }
if (!function_exists('data_set')) { function data_set() { return \PhpScoperExampleVendor\data_set(...func_get_args()); } }
if (!function_exists('fpow')) { function fpow() { return \PhpScoperExampleVendor\fpow(...func_get_args()); } }
if (!function_exists('get_error_handler')) { function get_error_handler() { return \PhpScoperExampleVendor\get_error_handler(...func_get_args()); } }
if (!function_exists('get_exception_handler')) { function get_exception_handler() { return \PhpScoperExampleVendor\get_exception_handler(...func_get_args()); } }
if (!function_exists('grapheme_str_split')) { function grapheme_str_split() { return \PhpScoperExampleVendor\grapheme_str_split(...func_get_args()); } }
if (!function_exists('head')) { function head() { return \PhpScoperExampleVendor\head(...func_get_args()); } }
if (!function_exists('last')) { function last() { return \PhpScoperExampleVendor\last(...func_get_args()); } }
if (!function_exists('mb_lcfirst')) { function mb_lcfirst() { return \PhpScoperExampleVendor\mb_lcfirst(...func_get_args()); } }
if (!function_exists('mb_ltrim')) { function mb_ltrim() { return \PhpScoperExampleVendor\mb_ltrim(...func_get_args()); } }
if (!function_exists('mb_rtrim')) { function mb_rtrim() { return \PhpScoperExampleVendor\mb_rtrim(...func_get_args()); } }
if (!function_exists('mb_trim')) { function mb_trim() { return \PhpScoperExampleVendor\mb_trim(...func_get_args()); } }
if (!function_exists('mb_ucfirst')) { function mb_ucfirst() { return \PhpScoperExampleVendor\mb_ucfirst(...func_get_args()); } }
if (!function_exists('value')) { function value() { return \PhpScoperExampleVendor\value(...func_get_args()); } }
if (!function_exists('when')) { function when() { return \PhpScoperExampleVendor\when(...func_get_args()); } }

return $loader;
