<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcb77cddf5dc70b14cbb2c9969aa4592c
{
    public static $files = array (
        '789fa7e65b753d89e599f2a4be9b8c69' => __DIR__ . '/..' . '/symfony/polyfill-php84/bootstrap.php',
        '1d359786b6fde501fa5ee6942455333c' => __DIR__ . '/..' . '/symfony/polyfill-php85/bootstrap.php',
        '813437524073141b671ac181387eb9b7' => __DIR__ . '/..' . '/illuminate/collections/functions.php',
        '762034e432ff3130c964e782b064d09b' => __DIR__ . '/..' . '/illuminate/collections/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PhpScoperExampleVendor\\Symfony\\Polyfill\\Php85\\' => 46,
            'PhpScoperExampleVendor\\Symfony\\Polyfill\\Php84\\' => 46,
            'PhpScoperExampleVendor\\Psr\\SimpleCache\\' => 39,
            'PhpScoperExampleVendor\\Psr\\Log\\' => 31,
            'PhpScoperExampleVendor\\Psr\\Container\\' => 37,
            'PhpScoperExampleVendor\\Illuminate\\Support\\' => 42,
            'PhpScoperExampleVendor\\Illuminate\\Contracts\\' => 44,
        ),
        'O' =>
        array (
            'Otomaties\\PhpScoperExample\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PhpScoperExampleVendor\\Symfony\\Polyfill\\Php85\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php85',
        ),
        'PhpScoperExampleVendor\\Symfony\\Polyfill\\Php84\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php84',
        ),
        'PhpScoperExampleVendor\\Psr\\SimpleCache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'PhpScoperExampleVendor\\Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'PhpScoperExampleVendor\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'PhpScoperExampleVendor\\Illuminate\\Support\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/collections',
            1 => __DIR__ . '/..' . '/illuminate/macroable',
            2 => __DIR__ . '/..' . '/illuminate/conditionable',
        ),
        'PhpScoperExampleVendor\\Illuminate\\Contracts\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'Otomaties\\PhpScoperExample\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PhpScoperExampleVendor\\Deprecated' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
        'PhpScoperExampleVendor\\NoDiscard' => __DIR__ . '/..' . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
        'PhpScoperExampleVendor\\ReflectionConstant' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcb77cddf5dc70b14cbb2c9969aa4592c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcb77cddf5dc70b14cbb2c9969aa4592c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcb77cddf5dc70b14cbb2c9969aa4592c::$classMap;

        }, null, ClassLoader::class);
    }
}
